# Generated by Django 6.0.5 on 2026-06-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user_type',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Company', 'Company')], default='Candidate', max_length=20),
        ),
    ]
