# Generated by Django 6.0.5 on 2026-06-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_job_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='Full-time', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='$60k-$90K', max_length=50),
            preserve_default=False,
        ),
    ]
