# Generated by Django 6.0.5 on 2026-06-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_job_job_type_job_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('New', 'New'), ('Shortlisted', 'Shortlisted'), ('Contacted', 'Contacted'), ('Rejected', 'Rejected')], default='New', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.business')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidate')),
            ],
            options={
                'unique_together': {('business', 'candidate')},
            },
        ),
    ]
