# Generated by Django 6.0.5 on 2026-06-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='premium_only',
            field=models.BooleanField(default=False),
        ),
    ]
