# Generated by Django 6.0.5 on 2026-06-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_job_premium_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='premium_only',
        ),
    ]
